import { useI18n } from '../i18n'
import type { WoynuErrorCode } from './shared/types'

// Interface text for Woynu AI (kept beside the feature so the main strings file stays focused).
// Amharic should be reviewed by a native speaker at the studio.

const en = {
  nav: 'Woynu AI',
  kicker: 'AI Style Consultation',
  title: 'Discover a cultural style made for you',
  intro:
    'Tell us about yourself, your occasion, and your preferred style. Woynu AI combines your preferences with Wolaita-inspired cultural fashion to create a personalized style concept.',
  cta: 'Create My Woynu Style',
  how1: 'Share your preferences',
  how1Text: 'Six short steps about you, your occasion, style, colours, and accessories.',
  how2: 'Woynu AI designs a concept',
  how2Text: 'Your choices become a design brief grounded in the Woynu Malala design library.',
  how3: 'Our designers make it real',
  how3Text: 'Love the concept? Send it to the studio to be designed and made for you.',
  disclaimer:
    'Woynu AI creates Wolaita-inspired design concepts for inspiration. They are not verified traditional garments — the Woynu Malala team remains the authority on authentic design.',
  step: 'Step',
  of: 'of',
  back: 'Back',
  next: 'Continue',
  required: 'Please make a choice to continue.',
  s1: 'About you',
  s1Help: 'These help shape the concept — they never limit what you can wear.',
  gender: 'Gender',
  age: 'Age group',
  s2: 'Occasion',
  s2Help: 'What will you be wearing it for?',
  s3: 'Style preference',
  s3Help: 'How close to tradition would you like it?',
  s4: 'Colours',
  s4Help: 'Choose one primary colour and, if you like, a secondary colour.',
  primary: 'Primary colour',
  secondary: 'Secondary colour (optional)',
  none: 'None',
  s5: 'Accessories',
  s5Help: 'Optional — choose any you like, or none.',
  s6: 'Anything else?',
  s6Label: 'Tell Woynu AI anything else',
  s6Placeholder: 'Example: “I want something elegant and traditional for my sister’s wedding.”',
  s6Privacy:
    'Your note is shared with the Woynu Malala team only if you request this design. Woynu AI reads it for style words, but never sends it word-for-word to the image model.',
  charsLeft: 'characters left',
  loadingTitle: 'Woynu AI is creating your style…',
  loadingNote: 'This can take up to a minute. Please keep this page open.',
  resultKicker: 'Your Woynu Style',
  inspirationLabel: 'Wolaita-inspired design concept',
  profile: 'Style Profile',
  occasion: 'Occasion',
  style: 'Style',
  palette: 'Colour palette',
  concept: 'Clothing concept',
  accessories: 'Accessories',
  inspiration: 'Design inspiration',
  notes: 'Your style notes',
  preview: 'Preview mode — this is a palette sketch, not an AI image. Connect an image provider to create real designs.',
  again: 'Generate Another Style',
  change: 'Try Different Preferences',
  download: 'Download image',
  contact: 'Contact Woynu Malala',
  loveTitle: 'Love this style?',
  loveText: 'Turn your AI-inspired concept into a real cultural fashion design with Woynu Malala.',
  request: 'Request This Design',
  errorTitle: 'We couldn’t create your style right now.',
  retry: 'Try Again',
  editChoices: 'Edit my choices',
  attached: 'Your Woynu AI style is attached to this request.',
  homeKicker: 'New · Woynu AI',
  tryKicker: 'Virtual try-on',
  tryTitle: 'See it on you',
  tryText: 'Upload a photo of yourself and Woynu AI will show you wearing this design.',
  tryTips: 'Best results: one person, facing the camera, good light, full body or waist up.',
  tryChoose: 'Choose a photo',
  tryChange: 'Choose a different photo',
  tryPrivacyTitle: 'How your photo is handled',
  tryPrivacy1: 'Your photo is resized on your device, and hidden location data is removed.',
  tryPrivacy2: 'It is sent once to our AI provider (OpenAI) only to create this preview.',
  tryPrivacy3: 'Woynu Malala does not store your photo, and it is not used to train AI models.',
  tryPrivacy4: 'Our provider may keep it for up to 30 days for safety checks, then deletes it.',
  tryConsent:
    'I confirm this is a photo of me (or I have the person’s permission), the person is an adult, and I agree to it being processed as described above.',
  tryButton: 'See It On Me',
  tryLoading: 'Woynu AI is dressing you in your design…',
  tryResultTitle: 'You, in your Woynu style',
  tryYourPhoto: 'Your photo',
  tryResultLabel: 'AI try-on preview',
  tryDisclaimer:
    'An AI preview of how the design could look on you — the final garment is tailored by the Woynu Malala team.',
  tryRemove: 'Remove my photo',
  tryAgain: 'Try another photo',
  tryDownload: 'Download try-on',
  tryAdultsOnly: 'Photo try-on is available when the age group is Young Adult, Adult, or Elder.',
  tryPreview: 'Preview mode — this shows your photo beside the sketch. Connect an image provider for a real AI try-on.',
  tryNotSaved: 'Your photo has not been saved anywhere.',
  tryPhotoError: 'We couldn’t read that photo. Please choose a JPG or PNG image.',
}

type Key = keyof typeof en

const am: Record<Key, string> = {
  nav: 'ወይኑ AI',
  kicker: 'የAI የአለባበስ ምክክር',
  title: 'ለእርስዎ የተዘጋጀ ባህላዊ ዘይቤ ያግኙ',
  intro:
    'ስለ ራስዎ፣ ስለ ዝግጅትዎ እና ስለሚመርጡት ዘይቤ ይንገሩን። ወይኑ AI ምርጫዎችዎን በወላይታ ባህል ከተነሳሳ ፋሽን ጋር በማጣመር ለእርስዎ የሚሆን የአለባበስ ሀሳብ ይፈጥራል።',
  cta: 'የወይኑ ዘይቤዬን ፍጠር',
  how1: 'ምርጫዎችዎን ያጋሩ',
  how1Text: 'ስለ እርስዎ፣ ዝግጅትዎ፣ ዘይቤዎ፣ ቀለሞችዎ እና ጌጣጌጦችዎ ስድስት አጭር ደረጃዎች።',
  how2: 'ወይኑ AI የዲዛይን ሀሳብ ያዘጋጃል',
  how2Text: 'ምርጫዎችዎ በወይኑ ማላላ የዲዛይን ቤተ-መጽሐፍት ላይ የተመሠረተ የዲዛይን መግለጫ ይሆናሉ።',
  how3: 'ዲዛይነሮቻችን እውን ያደርጉታል',
  how3Text: 'ሀሳቡን ወደዱት? ለእርስዎ እንዲዘጋጅ እና እንዲሰፋ ወደ ስቱዲዮው ይላኩት።',
  disclaimer:
    'ወይኑ AI በወላይታ ባህል የተነሳሱ የዲዛይን ሀሳቦችን ለመነሳሳት ይፈጥራል። እነዚህ የተረጋገጡ ባህላዊ አልባሳት አይደሉም — ትክክለኛውን ዲዛይን የሚያረጋግጠው የወይኑ ማላላ ቡድን ነው።',
  step: 'ደረጃ',
  of: 'ከ',
  back: 'ተመለስ',
  next: 'ቀጥል',
  required: 'ለመቀጠል እባክዎ ይምረጡ።',
  s1: 'ስለ እርስዎ',
  s1Help: 'እነዚህ ሀሳቡን ለመቅረጽ ይረዳሉ — የሚለብሱትን አይገድቡም።',
  gender: 'ጾታ',
  age: 'የዕድሜ ክልል',
  s2: 'ዝግጅት',
  s2Help: 'ለምን ዝግጅት ይለብሱታል?',
  s3: 'የዘይቤ ምርጫ',
  s3Help: 'ከባህሉ ምን ያህል ቅርብ እንዲሆን ይፈልጋሉ?',
  s4: 'ቀለሞች',
  s4Help: 'አንድ ዋና ቀለም እና ከፈለጉ ሁለተኛ ቀለም ይምረጡ።',
  primary: 'ዋና ቀለም',
  secondary: 'ሁለተኛ ቀለም (አማራጭ)',
  none: 'የለም',
  s5: 'ጌጣጌጦች',
  s5Help: 'አማራጭ — የወደዱትን ይምረጡ ወይም ምንም አይምረጡ።',
  s6: 'ሌላ ነገር አለ?',
  s6Label: 'ለወይኑ AI ሌላ ማንኛውንም ነገር ይንገሩ',
  s6Placeholder: 'ምሳሌ፦ “ለእህቴ ሠርግ የሚያምር ባህላዊ ልብስ እፈልጋለሁ።”',
  s6Privacy:
    'ማስታወሻዎ ለወይኑ ማላላ ቡድን የሚደርሰው ይህን ዲዛይን ከጠየቁ ብቻ ነው። ወይኑ AI የዘይቤ ቃላትን ብቻ ይወስዳል፤ ማስታወሻውን ቃል በቃል ለምስል ሞዴሉ አይልክም።',
  charsLeft: 'ቁምፊዎች ቀርተዋል',
  loadingTitle: 'ወይኑ AI ዘይቤዎን እየፈጠረ ነው…',
  loadingNote: 'ይህ እስከ አንድ ደቂቃ ሊወስድ ይችላል። እባክዎ ይህን ገጽ አይዝጉት።',
  resultKicker: 'የእርስዎ የወይኑ ዘይቤ',
  inspirationLabel: 'በወላይታ ባህል የተነሳሳ የዲዛይን ሀሳብ',
  profile: 'የዘይቤ መገለጫ',
  occasion: 'ዝግጅት',
  style: 'ዘይቤ',
  palette: 'የቀለም ቅንብር',
  concept: 'የልብስ ሀሳብ',
  accessories: 'ጌጣጌጦች',
  inspiration: 'የዲዛይን መነሻ',
  notes: 'የዘይቤ ማስታወሻዎችዎ',
  preview: 'የሙከራ ሁነታ — ይህ የቀለም ንድፍ ብቻ ነው እንጂ በAI የተፈጠረ ምስል አይደለም።',
  again: 'ሌላ ዘይቤ ፍጠር',
  change: 'ምርጫዎችን ቀይር',
  download: 'ምስሉን አውርድ',
  contact: 'ወይኑ ማላላን ያግኙ',
  loveTitle: 'ይህን ዘይቤ ወደዱት?',
  loveText: 'በAI የተነሳሳውን ሀሳብዎን ከወይኑ ማላላ ጋር ወደ እውነተኛ ባህላዊ ፋሽን ዲዛይን ይቀይሩት።',
  request: 'ይህን ዲዛይን ይዘዙ',
  errorTitle: 'ዘይቤዎን አሁን መፍጠር አልቻልንም።',
  retry: 'እንደገና ይሞክሩ',
  editChoices: 'ምርጫዎቼን አስተካክል',
  attached: 'የወይኑ AI ዘይቤዎ ከዚህ ጥያቄ ጋር ተያይዟል።',
  homeKicker: 'አዲስ · ወይኑ AI',
  tryKicker: 'በፎቶ መሞከሪያ',
  tryTitle: 'በእርስዎ ላይ ይመልከቱት',
  tryText: 'የራስዎን ፎቶ ይጫኑ፤ ወይኑ AI ይህን ዲዛይን ለብሰው ያሳይዎታል።',
  tryTips: 'ለተሻለ ውጤት፦ አንድ ሰው፣ ወደ ካሜራ የሚመለከት፣ ጥሩ ብርሃን፣ ሙሉ ሰውነት ወይም እስከ ወገብ።',
  tryChoose: 'ፎቶ ይምረጡ',
  tryChange: 'ሌላ ፎቶ ይምረጡ',
  tryPrivacyTitle: 'ፎቶዎ እንዴት እንደሚያዝ',
  tryPrivacy1: 'ፎቶዎ በመሣሪያዎ ላይ ይቀነሳል፤ የተደበቀ የቦታ መረጃም ይወገዳል።',
  tryPrivacy2: 'ይህን ቅድመ-እይታ ለመፍጠር ብቻ አንድ ጊዜ ወደ AI አቅራቢያችን (OpenAI) ይላካል።',
  tryPrivacy3: 'ወይኑ ማላላ ፎቶዎን አያስቀምጥም፤ AI ሞዴሎችን ለማሰልጠንም አይውልም።',
  tryPrivacy4: 'አቅራቢያችን ለደህንነት ቁጥጥር እስከ 30 ቀናት ሊያቆየው ይችላል፤ ከዚያም ይሰርዘዋል።',
  tryConsent:
    'ይህ የእኔ ፎቶ መሆኑን (ወይም የሰውየውን ፈቃድ እንዳገኘሁ)፣ ሰውየው አዋቂ መሆኑን እና ፎቶው ከላይ በተገለጸው መሠረት እንዲሠራበት መስማማቴን አረጋግጣለሁ።',
  tryButton: 'በእኔ ላይ አሳየኝ',
  tryLoading: 'ወይኑ AI ዲዛይኑን እያለበስዎት ነው…',
  tryResultTitle: 'እርስዎ፣ በወይኑ ዘይቤዎ',
  tryYourPhoto: 'የእርስዎ ፎቶ',
  tryResultLabel: 'የAI መሞከሪያ ቅድመ-እይታ',
  tryDisclaimer: 'ዲዛይኑ በእርስዎ ላይ እንዴት ሊታይ እንደሚችል የሚያሳይ የAI ቅድመ-እይታ ነው — የመጨረሻው ልብስ በወይኑ ማላላ ቡድን ይሰፋል።',
  tryRemove: 'ፎቶዬን አስወግድ',
  tryAgain: 'ሌላ ፎቶ ሞክር',
  tryDownload: 'ውጤቱን አውርድ',
  tryAdultsOnly: 'በፎቶ መሞከር የሚቻለው የዕድሜ ክልሉ ወጣት፣ አዋቂ ወይም አዛውንት ሲሆን ነው።',
  tryPreview: 'የሙከራ ሁነታ — ፎቶዎን ከንድፉ ጎን ያሳያል። ለእውነተኛ የAI መሞከሪያ የምስል አቅራቢ ያገናኙ።',
  tryNotSaved: 'ፎቶዎ የትም አልተቀመጠም።',
  tryPhotoError: 'ያንን ፎቶ ማንበብ አልቻልንም። እባክዎ JPG ወይም PNG ምስል ይምረጡ።',
}

const errorsEn: Record<WoynuErrorCode | 'network', string> = {
  consent_required: 'Please confirm the photo consent to continue.',
  invalid_photo: 'Please choose a clear JPG, PNG, or WebP photo.',
  not_allowed_for_age: 'Photo try-on is available for adults only.',
  invalid_input: 'Please check your choices and try again.',
  payload_too_large: 'Please shorten your note and try again.',
  method_not_allowed: 'We couldn’t create your style right now. Please try again.',
  rate_limited: 'You have created several styles in a short time. Please wait a few minutes and try again.',
  timeout: 'Creating your style took too long. Please try again.',
  content_rejected: 'We couldn’t create this style. Please adjust your choices and try again.',
  not_configured: 'Woynu AI is not available right now. Please try again later.',
  generation_failed: 'We couldn’t create your style right now. Please try again.',
  network: 'Please check your internet connection and try again.',
}

const errorsAm: Record<WoynuErrorCode | 'network', string> = {
  consent_required: 'ለመቀጠል እባክዎ የፎቶ ፈቃዱን ያረጋግጡ።',
  invalid_photo: 'እባክዎ ግልጽ የሆነ JPG፣ PNG ወይም WebP ፎቶ ይምረጡ።',
  not_allowed_for_age: 'በፎቶ መሞከር የሚቻለው ለአዋቂዎች ብቻ ነው።',
  invalid_input: 'እባክዎ ምርጫዎችዎን ያረጋግጡ እና እንደገና ይሞክሩ።',
  payload_too_large: 'እባክዎ ማስታወሻዎን ያሳጥሩ እና እንደገና ይሞክሩ።',
  method_not_allowed: 'ዘይቤዎን አሁን መፍጠር አልቻልንም። እባክዎ እንደገና ይሞክሩ።',
  rate_limited: 'በአጭር ጊዜ ውስጥ ብዙ ዘይቤዎችን ፈጥረዋል። እባክዎ ጥቂት ደቂቃዎች ቆይተው እንደገና ይሞክሩ።',
  timeout: 'ዘይቤዎን መፍጠር ረጅም ጊዜ ወሰደ። እባክዎ እንደገና ይሞክሩ።',
  content_rejected: 'ይህን ዘይቤ መፍጠር አልቻልንም። እባክዎ ምርጫዎችዎን አስተካክለው እንደገና ይሞክሩ።',
  not_configured: 'ወይኑ AI አሁን አይገኝም። እባክዎ ቆይተው ይሞክሩ።',
  generation_failed: 'ዘይቤዎን አሁን መፍጠር አልቻልንም። እባክዎ እንደገና ይሞክሩ።',
  network: 'እባክዎ የኢንተርኔት ግንኙነትዎን ያረጋግጡ እና እንደገና ይሞክሩ።',
}

export function useAiText() {
  const { lang } = useI18n()
  return {
    lang,
    a: (key: Key) => (lang === 'am' ? am[key] : en[key]),
    errorText: (code: WoynuErrorCode | 'network') => (lang === 'am' ? errorsAm[code] : errorsEn[code]),
  }
}
